config/routes.rb
Rails.application.routes.draw do
    
  resources :repairs do
	resources :feedbacks
  end
  
  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
	
	get 'stafflogin' => :staffnew
    post 'stafflogin' => :staffcreate
    get 'stafflogout' => :staffdestroy
    delete 'stafflogout' => :staffdestroy 
  end

  resources :repairs
  resources :customers
  resources :quantities
  resources :jobs
  resources :parts
  resources :staffs
  
  get 'home' => 'pages'
  get 'about' => 'pages#about', as: 'about'
  get 'admin' => 'pages#admin', as: 'admin'
  get '/jobs' => 'jobs#job'
  get '/repairs' => 'repairs#repair'
  get '/parts' => 'partrs#part'
  get '/quantities' => 'quantities#quantity'
  get '/customers' => 'customers#customer'
  get '/staffs' => 'staffs#staff'
  
  get 'search', :to => 'repairs#search'
  
  root 'pages#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/staff.rb
class Staff < ApplicationRecord
	has_many :repairs, dependent: :destroy
	has_secure_password
	validates_uniqueness_of :email
	validates :email, email_format: { message: "doesn't look like an email address" }
	
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  before_action :staffauthorise, :only => [:show, :new, :create, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end
  
  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff member was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff record was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :email, :phone, :dob, :ppsn, :startdate, :position, :salary, :password, :password_confirmation)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff, local: true) do |form| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :staff_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :staff_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :staff_phone %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_field :dob, id: :staff_dob %>
  </div>

  <div class="field">
    <%= form.label :pps_no %>
    <%= form.text_field :ppsn, id: :staff_ppsn %>
  </div>

  <div class="field">
    <%= form.label :startdate %>
    <%= form.date_field :startdate, id: :staff_startdate %>
  </div>

  <div class="field">
    <%= form.label :position %>
	<%= form.select :position, ['Mechanic', 'Sales', 'Manager', 'Intern', 'PartTime']%>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_field :salary, id: :staff_salary %>
  </div>
  
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :staff_password %>
  </div>
  
  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :staff_password_confirmation %>
  </div>
  
  <div class="actions">
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<div class="textcenter">Staff Links:< 
<%= link_to 'Repairs', repairs_path %> | 
<%= link_to 'Customers', customers_path %> | 
<%= link_to "Parts", parts_path %> | 
<%= link_to "Employees", staffs_path %> | 
<%= link_to "Admin", admin_path %> | 
<%=  link_to "Jobs", jobs_path %> >
</div>
<br />
<h2>Edit Employee Details</h2>

<%= render 'form', staff: @staff %>

<br />
< <%= link_to 'Show Details', @staff %> |
<%= link_to 'Employee List', staffs_path %> >

app/views/staffs/index.html.erb
<div class="textcenter">Staff Links:< 
<%= link_to 'Repairs', repairs_path %> | 
<%= link_to 'Customers', customers_path %> | 
<%= link_to "Parts", parts_path %> | 
<%= link_to "Employees", staffs_path %> | 
<%= link_to "Admin", admin_path %> | 
<%=  link_to "Jobs", jobs_path %> >
</div>
<h2>Employee List</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Start Date</th>
      <th>Position</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.email %></td>
        <td><%= staff.phone %></td>
        <td><%= staff.startdate.strftime("%d-%m-%Y") %></td>
        <td><%= staff.position %></td>
        <td><%= euro (staff.salary) %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

< <%= link_to 'Add New Employee', new_staff_path %> >

app/views/staffs/new.html.erb
<br />
<h2>Enter New Employee</h2>

<%= render 'form', staff: @staff %>

<br />
<%= link_to 'Employee List', staffs_path %>

app/views/staffs/show.html.erb
<div class="textcenter">Staff Links:< 
<%= link_to 'Repairs', repairs_path %> | 
<%= link_to 'Customers', customers_path %> | 
<%= link_to "Parts", parts_path %> | 
<%= link_to "Employees", staffs_path %> | 
<%= link_to "Admin", admin_path %> | 
<%=  link_to "Jobs", jobs_path %> >
</div>
<br />
<h2>Employee Details</h2>
<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @staff.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @staff.phone %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @staff.dob.strftime("%d-%m-%Y") %>
</p>

<p>
  <strong>Age Now:</strong>
  <%= (Time.now.to_date - @staff.dob).div 365 %> Years 
</p>

<p>
  <strong>PPS No.:</strong>
  <%= @staff.ppsn %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @staff.startdate.strftime("%d-%m-%Y") %>
</p>

<p>
  <strong>Position:</strong>
  <%= @staff.position %>
</p>

<p>
  <strong>Salary:</strong>
  <%= euro (@staff.salary) %>
</p>
<br />

< <%= link_to 'Edit Details', edit_staff_path(@staff) %> |
<%= link_to 'Employee List', staffs_path %> >