config/routes.rb
Rails.application.routes.draw do
    
  resources :repairs do
	resources :feedbacks
  end
  
  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
	
	get 'stafflogin' => :staffnew
    post 'stafflogin' => :staffcreate
    get 'stafflogout' => :staffdestroy
    delete 'stafflogout' => :staffdestroy 
  end

  resources :repairs
  resources :customers
  resources :quantities
  resources :jobs
  resources :parts
  resources :staffs
  
  get 'home' => 'pages'
  get 'about' => 'pages#about', as: 'about'
  get 'admin' => 'pages#admin', as: 'admin'
  get '/jobs' => 'jobs#job'
  get '/repairs' => 'repairs#repair'
  get '/parts' => 'partrs#part'
  get '/quantities' => 'quantities#quantity'
  get '/customers' => 'customers#customer'
  get '/staffs' => 'staffs#staff'
  
  get 'search', :to => 'repairs#search'
  
  root 'pages#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :repairs, dependent: :destroy
	has_many :feedbacks
	has_secure_password
	validates_uniqueness_of :email
	validates :email, email_format: { message: "doesn't look like an email address" }
	
	def self.search(query)
		where("name LIKE ?", "%#{query}%")
	end
	
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?	
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
 # before_action :authorise, :only => [:show, :new, :create, :edit, :update, :destroy]
 # before_action :staffauthorise, :only => [:show, :new, :create, :edit, :update, :destroy]
 
  # GET /customers
  # GET /customers.json
  def index
    #@customers = Customer.all
	@customers = Customer.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end
    
  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :address, :phone, :email, :password, :password_confirmation, :regular, :latitude, :longitude)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :customer_name %>
  </div>
	
  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :customer_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :customer_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :customer_email %>
  </div>
  
  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :customer_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :customer_longitude %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :customer_password %>
  </div>
  
  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :customer_password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :regular %>
    <%= form.check_box :regular, id: :customer_regular %>
  </div>

  <div class="actions">
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </div>
<% end %>

app/views/customers/_search.html.erb
<%= form_tag(search_path, method: :get) do %>
	<%=text_field_tag(:query, params[:query], placeholder: "Enter customer name") %>
	<%= submit_tag "Search" %>
<% end %>

app/views/customers/edit.html.erb
<br />
<h2>Edit Customer Profile</h2>

<%= render 'form', customer: @customer %>
<br />
< <%= link_to 'Show Profile', @customer %> >

app/views/customers/index.html.erb
<div class="textcenter">Staff Links:< 
<%= link_to 'Repairs', repairs_path %> | 
<%= link_to 'Customers', customers_path %> | 
<%= link_to "Parts", parts_path %> | 
<%= link_to "Employees", staffs_path %> | 
<%= link_to "Admin", admin_path %> | 
<%=  link_to "Jobs", jobs_path %> >
</div>
<h2>Customers List</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Regular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.address %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
        <td><%= customer.regular %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

< <%= link_to 'Add New Customer', new_customer_path %> >
<div align="right"><%= will_paginate @customers %></div>

app/views/customers/new.html.erb
<br />
<h2>Enter New Customer</h2>

<%= render 'form', customer: @customer %>
<br />

If your already registered: <%= link_to "Sign In Here", login_path %>
<br />

app/views/customers/show.html.erb
<br />
<h2>Customer Details</h2>
<br />
<p>
   <h3><small>Name:</small> 
   <%= @customer.name %></h3>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Regular:</strong>
  <%= @customer.regular %>
</p>

<p>How far from DIT = 
<%= @customer.distance_to("DIT Aungier St Dublin").round(2)%> Miles </p>

<p><strong>Nearby Customers:</strong></p> 
<ul>
	<% @customer.nearbys(10).each do |n| %>
		<li><%= link_to n.address %> ( <%= n.distance.round(2)%> miles)</li>
	<% end %>
</ul>
<br />
<h3>
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8&markers=#{@customer.latitude}%2C#{@customer.longitude}" %>
</h3>

<br />
< <%= link_to 'Edit Profile', edit_customer_path(@customer) %> | 
< <%= link_to 'Enter New Repair', new_repair_path %> >