config/routes.rb
Rails.application.routes.draw do
    
  resources :repairs do
	resources :feedbacks
  end
  
  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
	
	get 'stafflogin' => :staffnew
    post 'stafflogin' => :staffcreate
    get 'stafflogout' => :staffdestroy
    delete 'stafflogout' => :staffdestroy 
  end

  resources :repairs
  resources :customers
  resources :quantities
  resources :jobs
  resources :parts
  resources :staffs
  
  get 'home' => 'pages'
  get 'about' => 'pages#about', as: 'about'
  get 'admin' => 'pages#admin', as: 'admin'
  get '/jobs' => 'jobs#job'
  get '/repairs' => 'repairs#repair'
  get '/parts' => 'partrs#part'
  get '/quantities' => 'quantities#quantity'
  get '/customers' => 'customers#customer'
  get '/staffs' => 'staffs#staff'
  
  get 'search', :to => 'repairs#search'
  
  root 'pages#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/repair.rb
class Repair < ApplicationRecord
	belongs_to :job, :optional => true
	belongs_to :customer, :optional => true
	has_many :quantities, dependent: :destroy
	has_many :parts, through: :quantity
	has_many :feedbacks
	validates :repair_detail, presence: true
	validates :job, presence: true
	validates :customer, presence: true
	
	def self.search(query, current_page)
		if query
			page(current_page).where("description LIKE ?", "%#{query}%").order('id DESC')
		else
			page(current_page).order('id DESC') 
		end
	end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :set_repair, only: [:show, :edit, :update, :destroy]
  before_action :authorise, :only => [:new, :create]
  #before_action :staffauthorise, :only => [:new, :create, :edit, :update, :destroy]

  # GET /repairs
  # GET /repairs.json
  def index
    #@repairs = Repair.all
	@repairs = Repair.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /repairs/1
  # GET /repairs/1.json
  def show
  end

  def search
	@repairs = Repair.search params[:query], params[:page]
	unless @repairs.empty?
		render 'index'
	else
		flash[:notice] = 'No bicycle description matches that search'
		redirect_to repairs_path
	end
  end
  
  # GET /repairs/new
  def new
    @repair = Repair.new
  end

  # GET /repairs/1/edit
  def edit
  end

  # POST /repairs
  # POST /repairs.json
  def create
    @repair = Repair.new(repair_params)

    respond_to do |format|
      if @repair.save
        format.html { redirect_to @repair, notice: 'Repair was successfully created.' }
        format.json { render :show, status: :created, location: @repair }
      else
        format.html { render :new }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repairs/1
  # PATCH/PUT /repairs/1.json
  def update
    respond_to do |format|
      if @repair.update(repair_params)
        format.html { redirect_to @repair, notice: 'Repair was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair }
      else
        format.html { render :edit }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    @repair.destroy
    respond_to do |format|
      format.html { redirect_to repairs_url, notice: 'Repair was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair
      @repair = Repair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_params
      params.require(:repair).permit(:date_out, :cost_quote, :labour_cost, :total_cost, :customer_id, :job_id, :required_date, :description, :repair_type, :repair_detail, :repair_photo)
    end
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/views/repairs/_cust.html.erb
<%= form_with(model: repair, local: true) do |form| %>
  <% if repair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repair.errors.count, "error") %> prohibited this repair from being saved:</h2>

      <ul>
      <% repair.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.collection_select :customer_id, Customer.all, :id, :name, :value => @current_user.name %>
  </div>

  <div class="field">
    <%= form.label :Job_status %>
    <%= form.collection_select :job_id, Job.all, :id, :status, :value => "Waiting in Queue" %>
  </div>

  <div class="field">
    <%= form.label :required_date %>
    <%= form.date_field :required_date, id: :repair_required_date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :repair_description  %>
  </div>

  <div class="field">
    <%= form.label :select_bike_type %>
	<%= form.select :repair_type, ['City Bike    ', 'Racer', 'BMX', 'MTB', 'Kids', 'Electric     ']%>
  </div>

  <div class="field">
    <%= form.label :repair_detail %>
    <%= form.text_field :repair_detail, id: :repair_repair_detail %>
  </div>

  <div class="field">
    <%= form.label :Input_your_photo %>
    <%= form.text_field :repair_photo, id: :repair_repair_photo,:value => "bike.png" %>
  </div>
  
  <div class="actions">
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </div>
<% end %>

app/views/repairs/_form.html.erb
<%= form_with(model: repair, local: true) do |form| %>
  <% if repair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repair.errors.count, "error") %> prohibited this repair from being saved:</h2>

      <ul>
      <% repair.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_collected %>
    <%= form.date_field :date_out, id: :repair_date_out %>
  </div>

  <div class="field">
    <%= form.label :original_quote %>
    <%= form.text_field :cost_quote, id: :repair_cost_quote %>
  </div>

  <div class="field">
    <%= form.label :labour_cost %>
    <%= form.text_field :labour_cost, id: :repair_labour_cost %>
  </div>

  <div class="field">
    <%= form.label :total_cost %>
    <%= form.text_field :total_cost, id: :repair_total_cost %>
  </div>
  
  <div class="field">
    <%= form.label :customer_id %>
    <%= form.collection_select :customer_id, Customer.all, :id, :name, :include_blank => "Select from list" %>
  </div>

  <div class="field">
    <%= form.label :Job_status %>
    <%= form.collection_select :job_id, Job.all, :id, :status, :include_blank => "Select from list" %>
  </div>

  <div class="field">
    <%= form.label :required_date %>
    <%= form.date_field :required_date, id: :repair_required_date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :repair_description %>
  </div>

  <div class="field">
    <%= form.label :select_bike_type %>
	<%= form.select :repair_type, ['City Bike    ', 'Racer', 'BMX', 'MTB', 'Kids', 'Electric     ']%>
  </div>

  <div class="field">
    <%= form.label :repair_detail %>
    <%= form.text_field :repair_detail, id: :repair_repair_detail %>
  </div>

  <div class="field">
    <%= form.label :repair_photo %>
    <%= form.text_field :repair_photo, id: :repair_repair_photo %>
  </div>

  <div class="actions">
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </div>
<% end %>

app/views/repairs/_search.html.erb
<%= form_tag(search_path, method: :get) do %>
	<%=text_field_tag(:query, params[:query], placeholder: "Describe bicycle") %>
	<%= submit_tag "Search for Repair" %>
<% end %>

app/views/repairs/edit.html.erb
<div class="textcenter">Staff Links:< 
<%= link_to 'Repairs', repairs_path %> | 
<%= link_to 'Customers', customers_path %> | 
<%= link_to "Parts", parts_path %> | 
<%= link_to "Employees", staffs_path %> | 
<%= link_to "Admin", admin_path %> | 
<%=  link_to "Jobs", jobs_path %> >
</div>

<h2>Update Repair Details</h2>
<br />
<%= render 'form', repair: @repair %>
<br />
< <%= link_to 'Show Details', @repair %> |
<%= link_to 'Back to Repair List', repairs_path %> >

app/views/repairs/index.html.erb
<div class="textcenter">Staff Links:< 
<%= link_to 'Repairs', repairs_path %> | 
<%= link_to 'Customers', customers_path %> | 
<%= link_to "Parts", parts_path %> | 
<%= link_to "Employees", staffs_path %> | 
<%= link_to "Admin", admin_path %> | 
<%=  link_to "Jobs", jobs_path %> >
</div>
<div id="search" align="right">
	<%= render 'search' %>
</div>
<h2>Repairs List</h2>
<table>
  <thead>
    <tr>
      <th>Req. by </th>
      <th>/Total Due </th>
      <th>/Customer</th>
      <th>/Status</th>
      
      <th>/Desc.</th>
      <th>/Type</th>
      <th>/Details</th>
      <th>/Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repairs.reverse.each do |repair| %>
      <tr>
        <td><%= repair.required_date %></td>
        <td><%= euro (repair.total_cost) %></td>
        <td><%= repair.customer.name %></td>
        <td><%= repair.job.status %></td>
        
        <td><%= repair.description %></td>
        <td><%= repair.repair_type %></td>
        <td><%= repair.repair_detail %></td>
		<td><%= image_tag repair.repair_photo, :size => "50x50" %></td>
        <td><%= link_to 'Show', repair %></td>
        <td><%= link_to 'Edit', edit_repair_path(repair) %></td>
        <td><%= link_to 'Destroy', repair, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
< <%= link_to 'New Repair', new_repair_path %> >
<div align="right"><%= will_paginate @repairs %></div>

app/views/repairs/new.html.erb
<br />
<h2>Add New Repair</h2>

<%= render 'cust', repair: @repair %>
<br />

app/views/repairs/show.html.erb
<div class="textcenter">Staff Links:< 
<%= link_to 'Repairs', repairs_path %> | 
<%= link_to 'Customers', customers_path %> | 
<%= link_to "Parts", parts_path %> | 
<%= link_to "Employees", staffs_path %> | 
<%= link_to "Admin", admin_path %> | 
<%=  link_to "Jobs", jobs_path %> >
</div>

<h2>Repair Information</h2>
<br />
<table width="95%" border="0" cellpadding="5">
  <tr>
    <th scope="col">Staff Area</th>
    <th scope="col">Customer Description</th>
    <th scope="col">Photo</th>
  </tr>
  <tr>
    <td><small><em>Date Collected:</small></em> <%= @repair.date_out %></td>
    <td><small><em>Name:</small></em> <%= @repair.customer.name %></td>
    <td rowspan="5"><%= image_tag(@repair.repair_photo) %></td>
  </tr>
  <tr>
    <td><small><em>Quoted:</small></em> <%= euro (@repair.cost_quote) %></td>
    <td><small><em>Required for:</small></em> <%= @repair.required_date %></td>
  </tr>
  <tr>
    <td><small><em>Labour:</small></em> <%= @repair.labour_cost %></td>
    <td><small><em>Description:</small></em> <%= @repair.description %></td>
  </tr>
  <tr>
    <td><small><em>Total cost:</small></em> <%= @repair.total_cost %></td>
    <td><small><em>Bike type:</small></em> <%= @repair.repair_type %></td>
  </tr>
  <tr>
    <td><small><em>Current Status:</small></em> <%= @repair.job.status %></td>
    <td><small><em>Repair detail:</small></em> <%= @repair.repair_detail %></td>
  </tr>
</table>
<br />
<div class="center">
<h4>We'd Love Your Feedback</h4>
	<%= form_for([@repair, Feedback.new]) do |form| %>	
		<%= form.text_area :content, :rows => 2, :cols => 80 %>
			<div class="actions">
				<%= form.submit "Post Feedback",({:class => 'btn btn-primary'}) %>
			</div>
	<% end %>

<br />
<% if @repair.feedbacks.empty? %>
	<h4>You are the first to give us feedback</h4>
<% else %>
	<h4>Feedback Received:</h4>
	<% @repair.feedbacks.reverse.each do |feedback| %>
		<li><%= feedback.content %> | 
		<em>Posted <%= time_ago_in_words(feedback.created_at) %> ago by <%= feedback.customer.name %></em><br /></li>
	<% end %>
<% end %>
</div>