config/routes.rb
Rails.application.routes.draw do
    
  resources :repairs do
	resources :feedbacks
  end
  
  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
	
	get 'stafflogin' => :staffnew
    post 'stafflogin' => :staffcreate
    get 'stafflogout' => :staffdestroy
    delete 'stafflogout' => :staffdestroy 
  end

  resources :repairs
  resources :customers
  resources :quantities
  resources :jobs
  resources :parts
  resources :staffs
  
  get 'home' => 'pages'
  get 'about' => 'pages#about', as: 'about'
  get 'admin' => 'pages#admin', as: 'admin'
  get '/jobs' => 'jobs#job'
  get '/repairs' => 'repairs#repair'
  get '/parts' => 'partrs#part'
  get '/quantities' => 'quantities#quantity'
  get '/customers' => 'customers#customer'
  get '/staffs' => 'staffs#staff'
  
  get 'search', :to => 'repairs#search'
  
  root 'pages#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :repairs, dependent: :destroy
	has_many :feedbacks
	has_secure_password
	validates_uniqueness_of :email
	validates :email, email_format: { message: "doesn't look like an email address" }
	
	def self.search(query)
		where("name LIKE ?", "%#{query}%")
	end
	
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?	
end

app/models/discount.rb
class Discount < ApplicationRecord
	has_many :repairs, dependent: :destroy
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :repair
  belongs_to :customer
  validates :content, presence: true 
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :repairs, dependent: :destroy
end

app/models/part.rb
class Part < ApplicationRecord
	has_many :quantities, dependent: :destroy
	has_many :repairs, through:  :quantity
	validates :description, presence: true
	validates :description, uniqueness: true
	validates :unit_price, presence: true
end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :repair
  belongs_to :part
end

app/models/repair.rb
class Repair < ApplicationRecord
	belongs_to :job, :optional => true
	belongs_to :customer, :optional => true
	has_many :quantities, dependent: :destroy
	has_many :parts, through: :quantity
	has_many :feedbacks
	validates :repair_detail, presence: true
	validates :job, presence: true
	validates :customer, presence: true
	
	def self.search(query, current_page)
		if query
			page(current_page).where("description LIKE ?", "%#{query}%").order('id DESC')
		else
			page(current_page).order('id DESC') 
		end
	end
end

app/models/staff.rb
class Staff < ApplicationRecord
	has_many :repairs, dependent: :destroy
	has_secure_password
	validates_uniqueness_of :email
	validates :email, email_format: { message: "doesn't look like an email address" }
	
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :staffauthorise, :only => [:new, :create, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:status, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def signed_in?
		if session[:customer_id].nil?
			return
		else
			@current_user = Customer.find_by_id(session[:customer_id])
		end
	end
	
	def authorise
		unless signed_in? 
			session[:returned_to] = request.fullpath
			redirect_to login_path, :notice => "Please sign in to access this page"
		end
	end
	
	def euro (amount)
		number_to_currency(amount, :unit => '€')
	end
	
	def staffsigned_in?
		if session[:staff_id].nil?
			return
		else
			@staffcurrent_user = Staff.find_by_id(session[:staff_id])
		end
	end
	
	def staffauthorise
		unless staffsigned_in? 
			session[:returned_to] = request.fullpath
			redirect_to stafflogin_path, :notice => "Staff must sign in to access this page"
		end
		
	end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer"><div class="center">< 
<%= link_to 'Home', home_path %> | 
<%= link_to 'About', about_path %> | 
<%= link_to "Customer Login", login_path %> | 
<%=  link_to "Book a Repair", new_repair_path %> | 
			<% if !staffsigned_in? %>
				<%= link_to "Staff Login", stafflogin_path %>
			<% else %>
				<strong><%= @staffcurrent_user.name %></strong>, signed in: 
				<%= link_to "Logout", stafflogout_path %>
			<% end %> | 
<%=  link_to "Register Here", new_customer_path %> >
<br />
<small>DT354-3 Web Development 2 - Ruby on Rails Project -  7th March 2018</small>
</div></div>

app/views/layouts/_header.html.erb
<div class="header">
	<div class="center">
		<div class="textcenter">
			<% if !signed_in? %>
				< <%= link_to "Sign In", login_path %>
			<% else %>
				< Signed in as: <strong><%= @current_user.name %></strong>,
				<%= link_to "Sign Out", logout_path %>
			<% end %> 
			| <%= link_to 'Home', home_path %> | 
			<%= link_to 'About', about_path %> | 
			<%=  link_to "Book a Repair", new_repair_path %> | 
			<%=  link_to "Register Here", new_customer_path %> >
			</div>
		<table width="85%" border="0" cellpadding="2">
		  <tr>
			<td><%= link_to image_tag("ror.png", :alt => "Rails"), repairs_path %></td>
			<td><%= image_tag("RoR-BRS-logo.png", :alt => "Shop Logo") %></td>
		  </tr>
		</table>
	</div>
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bicycle Repair Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
	<%= render "layouts/header" %>	
		<div class="container">
			<div class="content">
				<% flash.each do |key, value| %>
				<div class="flash <%= key %>">
					<%= value %>
				</div>
			<% end %>
				<%= yield %>
			</div>
		</div>
	<%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<br />
<h2>About Us</h2>
<table width="90%">
  <tr>
    <td><%= image_tag("bicycle4.jpg", :alt => "Bike Repairs", class: "img-responsive center-block") %></td>
	<td><p>The bicycle you buy, and especially where you buy it, has a huge impact on your safety, comfort, and how much fun you have riding your bike! </p>
	<p>By purchasing your new bike from a professional bicycle store instead of from a supermarket or "discount" store, you receive numerous important advantages that will ensure a lifetime of cycling enjoyment.</p><p>If you need your bike fixed fast, you’ll want to bring it here. We offer a 48-hour guaranteed turnaround for all servicing and repairs. </p></td>
  </tr>	
</table>
<br />
<h3>You will find us here</h4>
<center><h3>
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=900x600&sensor=false&zoom=16&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8&markers=#{53.3385578}%2C#{-6.2665737}" %>
</h3></center>
<br />
<p>Ruby on Rails Assignment - Student: Peter Purfield, C15723545</p>
<br />

app/views/pages/admin.html.erb
<div class="textcenter">Staff Links:< 
<%= link_to 'Repairs', repairs_path %> | 
<%= link_to 'Customers', customers_path %> | 
<%= link_to "Parts", parts_path %> | 
<%= link_to "Employees", staffs_path %> | 
<%= link_to "Admin", admin_path %> | 
<%=  link_to "Jobs", jobs_path %> >
</div>
<h2>Admin Page</h2>

<br />
<center><p>This page is under construction</p>
<h4><em>I will complete if time allows</em></h4>
<p>Here's a mock-up of some ideas</p></center>
<br />
<h3>Totals</h3>
<ul>
	<li>Customers = <%=  Customer.count %></li>
	<li>Repairs = <%=  Repair.count %></li>
	<li>Employees = <%=  Staff.count %></li>
</ul>
<br />
<h3>Repairs Status</h3>
<h4>Waiting in queue | Work not started</h4>
<ol>
	<li>Fit wheel, Required for: 2018-02-25, Customer: Anita O'Brien, Total Price: €</li>
	<li>Fit chain, Required for: 2018-02-13, Customer: Joe Bloggs, Total Price: €</li>
	<li>Puncture, Required for: 2018-02-20, Customer: Peter P, Total Price: €</li>
	<li>Fix Buckle, Required for: 2018-02-27, Customer: Peter Jones, Total Price: €</li>
	<li>here.....</li>
	<li>and here..</li>
</ol>
<br />

<h4>Work in Progress | In workshop now</h4>
<ol>
	<li>Puncture, Required for: 2018-02-16, Customer: Frank Murphy, Total Price: €</li>
	<li>Fit 2 tyres, Required for: 2018-02-25, Customer: Mary Walsh, Total Price: €</li>
	<li>here.....</li>
	<li>and here..</li>
</ol>

<br />
<p>Ruby on Rails Exercise - Student: Peter Purfield, C15723545</p>
<br />

app/views/pages/home.html.erb
<br />
<h2>Welcome to our website</h2>
<br />
<%= image_tag("workshop.jpg", :alt => "Workshop", class: "img-responsive center-block") %>
<div class="textcenter">
<p>Ruby on Rails, CA Assignment - Student: Peter Purfield, C15723545
<%= link_to "<< GitHub link >>", "https://github.com/C15723545/BikeRepairShop", :target => "_blank" %></p>
<br />
<h4>Sign In or Register</h4>
<%= link_to "Login Here ", login_path, ({:class => 'btn btn-default'}) %>
<%=  link_to "Register Here", new_customer_path, ({:class => 'btn btn-default'}) %> <br /><br />
<h4>Log a Repair: <%=  link_to "Click here to book a repair", new_repair_path, ({:class => 'btn btn-warning'}) %></h4>
</div>

<br />
<h3>We're glad you dropped in...</h3>
<p>Whether the best part of your day is getting to work on two wheels, you live for the thrill of speeding down single-track in the middle of the woods or you spend all your free time on the road trying to get a little bit faster, your favourite bike shop is, above all, your sanctuary.</p>
<br />